insert into books values(1,'Charles Dickens','A Tale of Two Cities',1859);
insert into books values(2,'J. R. R. Tolkien','The Lord of the Rings',1954);
insert into books values(3,'Agatha Christie','And Then There Were None',1939);
insert into books values(4,'J. R. R. Tolkien','The Hobbit',1937);
insert into books values(5,'Cao Xueqin','Dream of the Red Chamber',1800);
insert into books values(6,'H. Rider Haggard','She',1887);
insert into books values(7,'Antoine de Saint-Exupéry','The Little Prince',1943);
insert into books values(8,'Dan Brown','The Da Vinci Code',2003);
insert into books values(9,'J. D. Salinger','The Catcher in the Rye',1951);
insert into books values(10,'Paulo Coelho','The Alchemist',1988);
insert into books values(11,'Johanna Spyri','Heidi',1880);
insert into books values(12,'Lucy Maud Montgomery','Anne of Green Gables',1908);
insert into books values(13,'Anna Sewell','Black Beauty',1877);
insert into books values(14,'Umberto Eco','The Name of the Rose',1980);
insert into books values(15,'E.B. White','Charlottes Web',1952);
insert into books values(16,'J.K. Rowling','Harry Potter and the Deathly Hallows',2007);
insert into books values(17,'Richard Bach','Jonathan Livingston Seagull',1970);
insert into books values(18,'Nikolai Ostrovsky','How the Steel Was Tempered',1932);
insert into books values(19,'Leo Tolstoy','War and Peace',1869);
insert into books values(20,'Jeffrey Archer','Kane and Abel',1979);
insert into books values(21,'Anne Frank','The Diary of Anne Frank',1947);
insert into books values(22,'Harper Lee','To Kill a Mockingbird',1960);
insert into books values(23,'Jacqueline Susann','Valley of the Dolls',1966);
insert into books values(24,'Margaret Mitchell','Gone with the Wind',1936);
insert into books values(25,'Gabriel García Márquez','One Hundred Years of Solitude',1967);
insert into books values(26,'Colleen McCullough','The Thorn Birds',1977);
insert into books values(27,'George Orwell','Nineteen Eighty-Four',1949);
insert into books values(28,'James Redfield','The Celestine Prophecy',1993);
insert into books values(29,'Mario Puzo','The Godfather',1969);
insert into books values(30,'Jiang Rong','Wolf Totem',2004);
insert into books values(31,'Peter Benchley','Jaws',1974);
insert into books values(32,'Jostein Gaarder','Sophies World',1991);
insert into books values(33,'Marilyn French','The Womens Room',1977);
insert into books values(34,'Erica Jong','Fear of Flying',1973);
insert into books values(35,'James Clavell','Shōgun',1975);
insert into books values(36,'Ken Follett','The Pillars of the Earth',1989);
insert into books values(37,'Patrick Süskind','Perfume',1985);
insert into books values(38,'Nicholas Evans','The Horse Whisperer',1995);
insert into books values(39,'Carlos Ruiz Zafón','The Shadow of the Wind',2001);
insert into books values(40,'Mitch Albom','Tuesdays with Morrie',1997);
insert into books values(41,'Erskine Caldwell','Gods Little Acre',1933);
insert into books values(42,'Susanna Tamaro','Follow Your Heart',1994);
insert into books values(43,'S. E. Hinton','The Outsiders',1967);
insert into books values(44,'Roald Dahl','Charlie and the Chocolate Factory',1964);
insert into books values(45,'Grace Metalious','Peyton Place',1956);
insert into books values(46,'Frank Herbert','Dune',1965);
insert into books values(47,'Albert Camus','The Plague',1947);
insert into books values(48,'Robert James Waller','The Bridges of Madison County',1992);
insert into books values(49,'Chinua Achebe','Things Fall Apart',1958);
insert into books values(50,'William Peter Blatty','The Exorcist',1971);
insert into books values(51,'Joseph Heller','Catch-22',1961);
insert into books values(52,'Ken Follett','Eye of the Needle',1978);
insert into books values(53,'Alice Sebold','The Lovely Bones',2002);
insert into books values(54,'Tomás Eloy Martínez','Santa Evita',1995);
insert into books values(55,'Khaled Hosseini','The Kite Runner',2003);